# Generated by Django 5.2.7 on 2025-10-02 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("extractions", "0001_initial"),
        ("papers", "0001_initial"),
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentConversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "agent_type",
                    models.CharField(
                        choices=[
                            ("extraction", "Extraction Agent"),
                            ("conversation", "Conversation Agent"),
                            ("workflow", "Workflow Agent"),
                        ],
                        max_length=50,
                    ),
                ),
                ("session_id", models.CharField(db_index=True, max_length=100)),
                (
                    "messages",
                    models.JSONField(
                        default=list, help_text="List of messages in the conversation"
                    ),
                ),
                (
                    "context",
                    models.JSONField(
                        default=dict,
                        help_text="Additional context for the conversation",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_conversations",
                        to="projects.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_conversations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["session_id", "agent_type"],
                        name="agents_agen_session_f95fa7_idx",
                    ),
                    models.Index(
                        fields=["project", "agent_type"],
                        name="agents_agen_project_d5400b_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AgentRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recommendation_type",
                    models.CharField(
                        choices=[
                            ("field_suggestion", "Field Suggestion"),
                            ("workflow_optimization", "Workflow Optimization"),
                            ("quality_improvement", "Quality Improvement"),
                            ("next_action", "Next Action"),
                            ("insight", "Data Insight"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "suggested_action",
                    models.JSONField(
                        default=dict, help_text="Suggested action details"
                    ),
                ),
                ("is_applied", models.BooleanField(default=False)),
                ("is_dismissed", models.BooleanField(default=False)),
                ("applied_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by_agent", models.CharField(max_length=50)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_recommendations",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-priority", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["project", "is_applied"],
                        name="agents_agen_project_3d6968_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AgentTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("extraction", "Feature Extraction"),
                            ("analysis", "Data Analysis"),
                            ("batch_processing", "Batch Processing"),
                            ("quality_check", "Quality Check"),
                            ("report_generation", "Report Generation"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        default=dict, help_text="Task configuration parameters"
                    ),
                ),
                (
                    "input_data",
                    models.JSONField(default=dict, help_text="Input data for the task"),
                ),
                (
                    "result",
                    models.JSONField(default=dict, help_text="Task execution results"),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Error message if task failed"
                    ),
                ),
                (
                    "progress",
                    models.IntegerField(
                        default=0, help_text="Progress percentage (0-100)"
                    ),
                ),
                ("total_items", models.IntegerField(default=0)),
                ("processed_items", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_tasks",
                        to="projects.project",
                    ),
                ),
                (
                    "related_extractions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="agent_tasks",
                        to="extractions.extraction",
                    ),
                ),
                (
                    "related_papers",
                    models.ManyToManyField(
                        blank=True, related_name="agent_tasks", to="papers.paper"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["project", "status"],
                        name="agents_agen_project_6dde68_idx",
                    ),
                    models.Index(
                        fields=["task_type", "status"],
                        name="agents_agen_task_ty_4dabdb_idx",
                    ),
                ],
            },
        ),
    ]
