# Generated by Django 5.2.7 on 2025-10-01 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "project_id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
                ("codebook_path", models.TextField(blank=True, null=True)),
                ("template_path", models.TextField(blank=True, null=True)),
                ("model", models.CharField(blank=True, max_length=255, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.BigIntegerField(blank=True, null=True)),
                ("updated_at", models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "projects",
                "ordering": ["-updated_at", "project_id"],
            },
        ),
        migrations.CreateModel(
            name="ProjectGroup",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("group_name", models.CharField(max_length=255)),
                ("fields_json", models.TextField()),
                ("codebook_path", models.TextField(blank=True, null=True)),
                ("prompt_path", models.TextField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.BigIntegerField(blank=True, null=True)),
                ("updated_at", models.BigIntegerField(blank=True, null=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feature_groups",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "db_table": "project_groups",
                "ordering": ["project", "group_name"],
                "unique_together": {("project", "group_name")},
            },
        ),
    ]
