# Generated by Django 5.2.7 on 2025-10-02 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Schema",
            fields=[
                (
                    "schema_id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "name_zh",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="中文名称"
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "category",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="分类"
                    ),
                ),
                (
                    "fields_definition",
                    models.TextField(help_text="JSON format schema definition"),
                ),
                (
                    "is_locked",
                    models.BooleanField(default=False, help_text="锁定后不可编辑"),
                ),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.CharField(default="1.0", max_length=50)),
                (
                    "usage_count",
                    models.IntegerField(default=0, help_text="被多少个项目使用"),
                ),
                (
                    "extraction_count",
                    models.IntegerField(default=0, help_text="总共提取了多少次"),
                ),
                ("created_by", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent_schema",
                    models.ForeignKey(
                        blank=True,
                        help_text="从哪个 Schema 复制而来",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="projects.schema",
                    ),
                ),
            ],
            options={
                "db_table": "schemas",
                "ordering": ["-updated_at", "schema_id"],
            },
        ),
        migrations.CreateModel(
            name="ProjectSchema",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("display_order", models.IntegerField(default=0, help_text="显示顺序")),
                ("is_active", models.BooleanField(default=True, help_text="是否启用")),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_schemas",
                        to="projects.project",
                    ),
                ),
                (
                    "schema",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_associations",
                        to="projects.schema",
                    ),
                ),
            ],
            options={
                "db_table": "project_schemas",
                "ordering": ["project", "display_order", "-added_at"],
                "unique_together": {("project", "schema")},
            },
        ),
    ]
