# Generated by Django 5.2.7 on 2025-10-01 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Paper",
            fields=[
                (
                    "paper_id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("title", models.TextField(blank=True, null=True)),
                ("citation", models.TextField(blank=True, null=True)),
                (
                    "citation_format",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("pdf_sha256", models.CharField(blank=True, max_length=128, null=True)),
                ("pdf_path", models.TextField(blank=True, null=True)),
                ("created_at", models.BigIntegerField(blank=True, null=True)),
                ("updated_at", models.BigIntegerField(blank=True, null=True)),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="papers",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "db_table": "papers",
                "ordering": ["-updated_at", "paper_id"],
            },
        ),
    ]
