# Generated by Django 5.2.7 on 2025-10-02 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("papers", "0001_initial"),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="paper",
            name="authors",
            field=models.TextField(
                blank=True, help_text="Comma-separated authors", null=True
            ),
        ),
        migrations.AddField(
            model_name="paper",
            name="bibtex_content",
            field=models.TextField(
                blank=True, help_text="Full BibTeX entry", null=True
            ),
        ),
        migrations.AddField(
            model_name="paper",
            name="citation_key",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Citation key extracted from BibTeX or custom",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="paper",
            name="cite_format",
            field=models.CharField(
                choices=[
                    ("bibtex", "BibTeX"),
                    ("ris", "RIS"),
                    ("endnote", "EndNote"),
                    ("other", "Other"),
                ],
                default="bibtex",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="paper",
            name="doi",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="paper",
            name="journal",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="paper",
            name="pdf_file",
            field=models.FileField(blank=True, null=True, upload_to="papers/pdfs/"),
        ),
        migrations.AddField(
            model_name="paper",
            name="year",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="paper",
            index=models.Index(
                fields=["citation_key"], name="papers_citatio_6b86a4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paper",
            index=models.Index(fields=["title"], name="papers_title_ca7740_idx"),
        ),
        migrations.AddIndex(
            model_name="paper",
            index=models.Index(fields=["year"], name="papers_year_054a3e_idx"),
        ),
    ]
