# Generated by Django 5.2.7 on 2025-10-02 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("papers", "0002_paper_authors_paper_bibtex_content_and_more"),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paper",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="papers",
                to="projects.project",
            ),
        ),
    ]
