# Generated by Django 5.2.7 on 2025-10-01 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("papers", "0001_initial"),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Extraction",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("profile", models.CharField(blank=True, max_length=255, null=True)),
                ("codebook_path", models.TextField(blank=True, null=True)),
                ("model", models.CharField(max_length=255)),
                ("base_url", models.TextField(blank=True, null=True)),
                ("mock", models.BooleanField(default=False)),
                ("prompt_tokens", models.IntegerField(blank=True, null=True)),
                ("status", models.CharField(max_length=64)),
                ("result_json", models.TextField(blank=True, null=True)),
                ("error_msg", models.TextField(blank=True, null=True)),
                ("batch_id", models.CharField(blank=True, max_length=255, null=True)),
                ("part_index", models.IntegerField(blank=True, null=True)),
                ("part_total", models.IntegerField(blank=True, null=True)),
                ("created_at", models.BigIntegerField(blank=True, null=True)),
                (
                    "paper",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extractions",
                        to="papers.paper",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extractions",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "db_table": "extractions",
                "ordering": ["-created_at"],
            },
        ),
    ]
