# Generated by Django 5.2.7 on 2025-10-02 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("extractions", "0001_initial"),
        ("papers", "0003_alter_paper_project"),
        ("projects", "0002_schema_projectschema"),
    ]

    operations = [
        migrations.AddField(
            model_name="extraction",
            name="extracted_data",
            field=models.TextField(
                blank=True,
                help_text="JSON format extracted data with confidence scores",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="extraction",
            name="extraction_method",
            field=models.CharField(
                choices=[
                    ("ai", "AI Extraction"),
                    ("manual", "Manual Entry"),
                    ("hybrid", "AI + Manual"),
                ],
                default="ai",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="extraction",
            name="schema",
            field=models.ForeignKey(
                blank=True,
                help_text="使用的 Schema",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="extractions",
                to="projects.schema",
            ),
        ),
        migrations.AddField(
            model_name="extraction",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="extraction",
            name="model",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="extraction",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("verified", "Verified"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=64,
            ),
        ),
        migrations.AddIndex(
            model_name="extraction",
            index=models.Index(
                fields=["project", "schema", "status"],
                name="extractions_project_d7d349_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="extraction",
            index=models.Index(
                fields=["paper", "schema"], name="extractions_paper_i_e710fe_idx"
            ),
        ),
    ]
